name: Publish to PyPI

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install poetry

      - run: poetry install --extras docs

      - run: poetry run sphinx-build -b html docs imo_vmdb/built_docs

      - run: poetry build

      - uses: pypa/gh-action-pypi-publish@release/v1
